"""empty message

Revision ID: 368b55029129
Revises: 5257cbf6c442
Create Date: 2020-11-25 20:21:43.324602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368b55029129'
down_revision = '5257cbf6c442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_geolocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('longitude'),
    sa.UniqueConstraint('radius')
    )
    op.create_table('model_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification')
    )
    op.create_table('model_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_login'),
    sa.UniqueConstraint('user_password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_user')
    op.drop_table('model_notification')
    op.drop_table('model_geolocation')
    # ### end Alembic commands ###
